### ISSUE TITLE
fix: update unit to area mapping

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/oplog-api#132]
Stuff that is to be removed (meaning it shouldn't be linked anymore and not be presented as a choice when making new logs):

"A2 - 1000" for area A2

New links that should be added:

"B2 - 1900" for area B2
and
"B3 - MHP" for area B3

**Comment by bonyfusbouvet** [comment]
@mikkel1ea forgot to assign this to you. Changes are in dev and prod.
