### ISSUE TITLE
feat: add polly retries when creating, updating, and deleting indexed documents in azure cognitive search

### ISSUE THREAD

**Issue by bonyfusbouvet** [equinor/oplog-api#133]
Use the following documentation,

https://www.thepollyproject.org/

**Comment by vehecap** [comment]
@bonyfusbouvet I'm adding this to the project board. If there are any updates relevant to the issue, please add them here.

**Comment by bonyfusbouvet** [comment]
@vehecap I think we should close this. Don't need to add polly IMO. I have added manual retries and it works nicely. No need to pull an extra dependency to the code.

**Comment by vehecap** [comment]
@bonyfusbouvet agree. As long as the underlying issue has been resolved, there's no need to add extra dependencies. Closing
