### ISSUE TITLE
fix(Azure AI search): text search

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/oplog-api#134]
How to recreate: When searching for spesific terms in log text e.g. "trykkmåling" only the complete word is sufficient. For instance if you wrote out "trykkmålin" you wont find anything. 

@bonyfusbouvet has worked on this issue previously where there was some issues with special characters used in tags (e.g. "H-4085" or similar). These type of tags follow the same example as above, it would find it if it was a exact match, but not if your just on you're way there.

**Comment by mikkel1ea** [comment]
Something that we can use as a help to optimize for this can be to look at a concrete example that I found. 
Some of the tags that are in use:
- CA-6001
- CA-6002
- CA-6003
- CA-6004

"Tags" as they are popularly called but in our system it's just a part of the log text string. Hypothetically let's say these tags are closely related to eachother, so that it was plausible I would want to search for "CA-600" and find any corresponding matches within that group. Right now we cant because we would have to type out the entire tag.

**Comment by eobrequinor** [comment]
In order to get result for "trykkmåling" when searching for "trykkmåli" we can utilize [prefix queries](https://learn.microsoft.com/en-us/azure/search/query-simple-syntax#prefix-queries). 

This, alone, will not be able to handle special characters such as "CA-6001". I think we have to choose a different [search analyzer](https://learn.microsoft.com/en-us/azure/search/search-query-partial-matching). I will read more about the analyzers.

**Comment by eobrequinor** [comment]
We could create a custom analyzer:

Using Keyword analyzer would not split the word "CA-600" into two words. However, Keyword is case sensitive. So we could us a recommended custom anaylzer:


A recommended combination is the [keyword tokenizer](https://lucene.apache.org/core/6_6_1/analyzers-common/org/apache/lucene/analysis/core/KeywordTokenizer.html) with a [lower-case token filter](https://lucene.apache.org/core/6_6_1/analyzers-common/org/apache/lucene/analysis/core/LowerCaseFilter.html). By itself, the built-in [keyword analyzer](https://lucene.apache.org/core/6_6_1/analyzers-common/org/apache/lucene/analysis/core/KeywordAnalyzer.html) doesn't lower-case any upper-case text, which can cause queries to fail. A custom analyzer gives you a mechanism for adding the lower-case token filter.
