### ISSUE TITLE
fix: Y-6100 Unit overlapping items

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/oplog-api#142]
There are two units both named Y-6100 that's under Y area in Oplog. This goes for both the filter menu and when selecting to make a new log. 

![Image](https://github.com/equinor/oplog-api/assets/111305377/8e36104f-5c07-4dde-9338-7b1e3ffeadab)

This leads to people choosing one of them, and when trying to filter for it later have to guess the correct one in order to find it again. 

What we need to do: Move all logs from one of the Y-6100 to the other, and make the now empty unit group unavailable so that for the future the same "double-booking" doesn't occur.

**Comment by bonyfusbouvet** [comment]
@mikkel1ea fixed in dev and production dbs.
