### ISSUE TITLE
fix(search): searching for end or middle of a string

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/oplog-api#143]
Example: If there is a word "Something" you would have to start typing "Some..." or "So..." to find it. 
If you start at the other end with "thing" you won't find the logs with "Something" in it. 
Same goes for "meth" which won't make you find "Something".

**Comment by mikkel1ea** [comment]
@emilobrestad this was the issue I was talking about regarding search this morning.
Another example is if you have a log text that contains '06-pt-303' and you want to find this by searching for '303'

**Comment by eobrequinor** [comment]
If you want to be able to show "something" when typing "meth" it would produce alto more responses - which could be less intuitive in my opinion. Could try to make a custom analyzer which does that - and see if it is worth it. 

I know a solution for the other example. Currently we are replacing words such as "06-pt-303" into "06pt303". Instead, we could replace "-" with space - which would turn  "06-pt-303"  into a three separate words "06 pt 303"

**Comment by mikkel1ea** [comment]
I think it's safe to ignore meth, it's just going to lead us down a road of trickery I suppose. 
The second option seems good, because based of the feedback on the search functionality it's usually using these tags with '-' in them as examples. So that would mean one could search for any part of a tag.

**Comment by mikkel1ea** [comment]
Resolved through the addition of ngram
