### ISSUE TITLE
chore: reduce amount of "Type" in filters

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/oplog-api#50]
I have asked the users to make us a list of which Types they want available, will add it here when I have received it.

**Comment by mikkel1ea** [comment]
* These are validated and are the Types that should be accessible in filter dropdown*
@FredrikMWold @emilobrestad  

Beredskap
Blend
Drift
Kjemikalier/Olje
Lab
Miljø
Prod-Opt
Rev.Stans
VDL AUT
VDL EL
VDL MEK/MRV
MldTilVdl

**Comment by FredrikMWold** [comment]
MldTilVdl og VDL-MEK er typer som eksistere fra før av
